Table users {
  id integer [primary key]
  username varchar
  password password
}

table items {
  id integer [primary key]
  title varcahar
  user_id integer [ref: > users.id]
  type_id integer [ref: - items_types.id]
  qty integer [not null, default: 1]
}

table items_photos {
  id integer [pk]
  item_id integer [ref: > items.id, not null]
  name varcahr
  url varchar [not null]
}

table items_types {
  id integer [pk]
  Title varchar [not null]
}

table types_parameters {
  id integer [pk]
  title varchar [not null]
  description text
}

table types_2_parameters {
  type_id integer [ref: > items_types.id, not null]
  parameter_id integer [ref: > types_parameters.id, not null]
}

table items_parameter_value {
  item_id integer [ref: > items.id, not null]
  paramenter_id integer [ref: > types_parameters.id, not null]
  value varchar [not null]
}