version: '3.9'

services:
  backend:
    build: .
    ports:
      - 8080:3000
    volumes:
      - ./:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: oddbox
      MARIADB_ROOT_PASSWORD: SwordFish
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306