version: '3.9'

services:
  backend:
    build: .
    ports:
      - 8080:3000
    volumes:
      - ./:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306